const DB_KEY='egames_admin_v2';
const AUTH_KEY='egames_admin_auth';
const CREDENTIALS={user:'admin',pass:'egames2026'};
const emptyDB={config:{name:'E-Games',date:'',place:'',format:'4x4',players:4},teams:[],matches:[],results:[],notices:[]};
const pages={dashboard:{title:'Dashboard do campeonato',sub:'Acompanhe tudo que está acontecendo na organização.'},inscricoes:{title:'Inscrições',sub:'Cadastre, revise e aprove as equipes do campeonato.'},equipes:{title:'Equipes',sub:'Gerencie somente as equipes cadastradas pela organização.'},chaveamento:{title:'Chaveamento',sub:'Monte os confrontos usando apenas equipes aprovadas.'},partidas:{title:'Partidas',sub:'Cadastre horários, confrontos e status.'},resultados:{title:'Resultados',sub:'Registre os placares das partidas realizadas.'},avisos:{title:'Avisos',sub:'Publique comunicados para a organização do campeonato.'},configuracoes:{title:'Configurações',sub:'Defina os dados principais do campeonato.'}};
function fresh(){return JSON.parse(JSON.stringify(emptyDB))}
function load(){try{const raw=JSON.parse(localStorage.getItem(DB_KEY)||'null');if(!raw)return fresh();return {config:{...emptyDB.config,...(raw.config||{})},teams:Array.isArray(raw.teams)?raw.teams:[],matches:Array.isArray(raw.matches)?raw.matches:[],results:Array.isArray(raw.results)?raw.results:[],notices:Array.isArray(raw.notices)?raw.notices:[]}}catch{return fresh()}}
function save(db){localStorage.setItem(DB_KEY,JSON.stringify(db))}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function uid(){return (window.crypto&&typeof window.crypto.randomUUID==='function'?window.crypto.randomUUID():Date.now()+'-'+Math.random())}
function isAuth(){return sessionStorage.getItem(AUTH_KEY)==='1'}
function guard(){if(!isAuth())location.href='login.html'}
function nav(){const el=document.getElementById('sidebar');el.innerHTML=`<div class="brand"><div class="brand-mark">E</div><div><strong>E-GAMES</strong><small>CAMPEONATO 4x4</small></div></div><div class="menu-label">MENU PRINCIPAL</div><nav class="nav">${[['dashboard','▦','Dashboard'],['inscricoes','▣','Inscrições'],['equipes','♙','Equipes'],['chaveamento','⌗','Chaveamento'],['partidas','◷','Partidas'],['resultados','✓','Resultados'],['avisos','!','Avisos'],['configuracoes','⚙','Configurações']].map(x=>`<a href="#${x[0]}" data-nav="${x[0]}">${x[1]}<span>${x[2]}</span></a>`).join('')}</nav><div class="sidebar-bottom"><span class="online-dot"></span>Sistema online<button id="logout">Sair</button></div>`;document.querySelectorAll('[data-nav]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();go(a.dataset.nav)}));document.getElementById('logout').onclick=()=>{sessionStorage.removeItem(AUTH_KEY);location.href='login.html'}}
function go(page){if(!pages[page])page='dashboard';document.body.dataset.page=page;document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===page));document.getElementById('breadcrumb').textContent='Início / '+(page==='dashboard'?'Dashboard':pages[page].title);document.getElementById('pageTitle').textContent=pages[page].title;document.getElementById('pageSubtitle').textContent=pages[page].sub;renderPage(page);history.replaceState(null,'','#'+page)}
function shell(html){document.getElementById('pageContent').innerHTML=html}
function empty(text){return `<div class="empty">${text}</div>`}
function dashboard(){const db=load();shell(`<div class="stats-grid"><div class="stat-card"><div class="stat-icon">♙</div><div><span>Equipes</span><strong>${db.teams.filter(t=>t.status==='approved').length}</strong><small>aprovadas</small></div></div><div class="stat-card"><div class="stat-icon">▣</div><div><span>Inscrições</span><strong>${db.teams.filter(t=>t.status==='pending').length}</strong><small>pendentes</small></div></div><div class="stat-card"><div class="stat-icon">◷</div><div><span>Partidas</span><strong>${db.matches.length}</strong><small>cadastradas</small></div></div><div class="stat-card"><div class="stat-icon">✓</div><div><span>Resultados</span><strong>${db.results.length}</strong><small>finalizados</small></div></div></div><div class="dashboard-grid"><section class="panel"><div class="panel-head"><div><h2>Próximas partidas</h2><p>Confrontos cadastrados pela organização.</p></div><a class="link" href="#partidas" data-nav="partidas">Gerenciar</a></div><div class="list">${db.matches.filter(m=>m.status!=='done').slice(0,6).map(m=>`<div class="list-row"><span><strong>${esc(m.teamA)}</strong> × <strong>${esc(m.teamB)}</strong><br><small>${esc(m.phase||'Partida')} · ${esc(m.date||'Data a definir')}</small></span><span class="status pending">Agendada</span></div>`).join('')||empty('Nenhuma partida cadastrada.')}</div></section><section class="panel"><div class="panel-head"><div><h2>Últimas inscrições</h2><p>Equipes aguardando análise.</p></div><a class="link" href="#inscricoes" data-nav="inscricoes">Ver inscrições</a></div><div class="list">${db.teams.slice(-6).reverse().map(t=>`<div class="list-row"><span><strong>${esc(t.name)}</strong><br><small>${esc(t.captain||'Sem capitão')}</small></span><span class="status ${t.status==='approved'?'approved':'pending'}">${t.status==='approved'?'Aprovada':'Pendente'}</span></div>`).join('')||empty('Nenhuma inscrição cadastrada.')}</div></section></div><section class="panel"><div class="panel-head"><div><h2>Ações rápidas</h2><p>Acesse as tarefas mais usadas.</p></div></div><div class="quick-actions"><a href="#inscricoes" data-nav="inscricoes">+ Nova inscrição</a><a href="#chaveamento" data-nav="chaveamento">Montar chaveamento</a><a href="#partidas" data-nav="partidas">Cadastrar partida</a><a href="#avisos" data-nav="avisos">Publicar aviso</a></div></section>`);bindLinks()}
function registrations(){
 const db=load();
 shell(`<div class="page-stats"><div class="mini-card"><span>Total</span><strong>${db.teams.length}</strong></div><div class="mini-card"><span>Pendentes</span><strong>${db.teams.filter(t=>t.status==='pending').length}</strong></div><div class="mini-card"><span>Aprovadas</span><strong>${db.teams.filter(t=>t.status==='approved').length}</strong></div></div><section class="panel"><div class="toolbar"><div><h2>Inscrições recebidas</h2><p>Nenhuma equipe é criada automaticamente.</p></div><div style="display:flex;gap:8px;align-items:center"><div class="search">⌕<input id="searchIns" placeholder="Pesquisar equipe..."></div><button class="btn-primary" id="newRegistration">+ Nova</button></div></div><div class="table-scroll"><table><thead><tr><th>Equipe</th><th>Capitão</th><th>Turma</th><th>Jogadores</th><th>Status</th><th>Ações</th></tr></thead><tbody id="insTable"></tbody></table></div></section>`);
 const render=()=>{
  const q=(document.getElementById('searchIns').value||'').toLowerCase();
  const rows=db.teams.filter(t=>t.name.toLowerCase().includes(q)).map(t=>`<tr><td><strong>${esc(t.name)}</strong><br><small>${esc(t.responsible||'')}</small></td><td>${esc(t.captain||'—')}</td><td>${esc(t.className||'—')}</td><td>${(t.players||[]).length}</td><td><span class="status ${t.status==='approved'?'approved':'pending'}">${t.status==='approved'?'Aprovada':'Pendente'}</span></td><td><button class="btn-secondary" data-view="${t.id}">Ver</button> ${t.status!=='approved'?`<button class="btn-primary" data-approve="${t.id}">Aprovar</button>`:`<button class="btn-danger" data-remove="${t.id}">Remover</button>`}</td></tr>`).join('');
  document.getElementById('insTable').innerHTML=rows||`<tr><td colspan="6">${empty('Nenhuma inscrição cadastrada.')}</td></tr>`;
 };
 document.getElementById('searchIns').oninput=render;
 document.getElementById('newRegistration').onclick=newRegistration;
 document.getElementById('insTable').onclick=e=>{
  const b=e.target.closest('button'); if(!b)return;
  const id=b.dataset.approve||b.dataset.remove||b.dataset.view; const t=db.teams.find(x=>x.id===id); if(!t)return;
  if(b.dataset.approve){t.status='approved';save(db);registrations()}
  else if(b.dataset.remove){db.teams=db.teams.filter(x=>x.id!==id);save(db);registrations()}
  else viewTeam(t);
 };
 render();
}
function newRegistration(){modal(`<h2>Nova inscrição</h2><p>Cadastre uma equipe diretamente no painel.</p><form id="regForm" class="form-grid"><label>Nome da equipe<input name="name" required></label><label>Capitão<input name="captain" required></label><label>Turma<input name="className"></label><label>Contato<input name="responsible"></label><label class="full">Jogadores<input name="players" placeholder="Nome 1, Nome 2, Nome 3, Nome 4" required></label><div class="full modal-actions"><button type="button" class="btn-secondary" data-close>Cancelar</button><button class="btn-primary">Salvar inscrição</button></div></form>`);document.getElementById('regForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),db=load();db.teams.push({id:uid(),name:f.get('name').trim(),captain:f.get('captain').trim(),className:f.get('className').trim(),responsible:f.get('responsible').trim(),players:f.get('players').split(',').map(x=>({name:x.trim()})).filter(x=>x.name),status:'pending',createdAt:new Date().toISOString()});save(db);closeModal();registrations()};bindClose()}
function viewTeam(t){modal(`<h2>${esc(t.name)}</h2><p>Capitão: ${esc(t.captain||'—')} · Turma: ${esc(t.className||'—')} · Contato: ${esc(t.responsible||'—')}</p>${(t.players||[]).map((p,i)=>`<p><strong>Jogador ${i+1}:</strong> ${esc(p.name||'')}</p>`).join('')}<div class="modal-actions"><button class="btn-secondary" data-close>Fechar</button></div>`);bindClose()}
function teams(){const db=load();shell(`<section class="panel"><div class="toolbar"><div><h2>Equipes aprovadas</h2><p>Os dados vêm das inscrições salvas no sistema.</p></div><div class="search">⌕<input id="searchTeams" placeholder="Pesquisar equipe..."></div></div><div id="teamsGrid" class="teams-grid"></div></section>`);const render=()=>{const q=(document.getElementById('searchTeams').value||'').toLowerCase();document.getElementById('teamsGrid').innerHTML=db.teams.filter(t=>t.status==='approved'&&t.name.toLowerCase().includes(q)).map(t=>`<article class="team-card"><h3>${esc(t.name)}</h3><p><strong>Capitão:</strong> ${esc(t.captain||'—')}</p><p><strong>Turma:</strong> ${esc(t.className||'—')}</p><p><strong>Jogadores:</strong> ${(t.players||[]).length}</p></article>`).join('')||empty('Nenhuma equipe aprovada.')};document.getElementById('searchTeams').oninput=render;render()}
function bracket(){const db=load();shell(`<div class="notice-box"><strong>Como funciona</strong><p>O sistema usa apenas equipes aprovadas. Se houver menos de duas equipes, nenhum confronto será criado.</p></div><div style="margin:18px 0"><button class="btn-primary" id="generateBracket">Gerar chaveamento</button></div><div id="bracket" class="bracket"></div>`);const render=()=>{const b=document.getElementById('bracket');if(!db.matches.length){b.innerHTML=empty('Nenhum chaveamento criado.');return}const rounds={};db.matches.forEach(m=>(rounds[m.phase||'1ª rodada']??=[]).push(m));b.innerHTML=Object.entries(rounds).map(([r,ms])=>`<section class="round"><h3>${esc(r)}</h3>${ms.map(m=>`<div class="match"><strong>${esc(m.teamA)}</strong><div class="vs">×</div><strong>${esc(m.teamB)}</strong><small>${esc(m.date||'Data a definir')}</small></div>`).join('')}</section>`).join('')};document.getElementById('generateBracket').onclick=()=>{const a=db.teams.filter(t=>t.status==='approved');if(a.length<2)return alert('É preciso ter pelo menos 2 equipes aprovadas.');db.matches=[];for(let i=0;i<a.length-1;i+=2)db.matches.push({id:uid(),phase:'1ª rodada',teamA:a[i].name,teamB:a[i+1].name,date:'',status:'scheduled'});save(db);bracket()};render()}
function matches(){
 const db=load();
 shell(`<section class="panel"><div class="toolbar"><div><h2>Partidas cadastradas</h2><p>Registre e finalize os confrontos.</p></div><button class="btn-primary" id="newMatch">+ Nova partida</button></div><div class="table-scroll"><table><thead><tr><th>Fase</th><th>Confronto</th><th>Data</th><th>Status</th><th>Ações</th></tr></thead><tbody id="matchesTable"></tbody></table></div></section>`);
 const render=()=>{
  const rows=db.matches.map(m=>`<tr><td>${esc(m.phase)}</td><td>${esc(m.teamA)} × ${esc(m.teamB)}</td><td>${esc(m.date||'—')}</td><td><span class="status ${m.status==='done'?'done':'pending'}">${m.status==='done'?'Finalizada':'Agendada'}</span></td><td>${m.status!=='done'?`<button class="btn-primary" data-finish="${m.id}">Registrar resultado</button>`:'—'}</td></tr>`).join('');
  document.getElementById('matchesTable').innerHTML=rows||`<tr><td colspan="5">${empty('Nenhuma partida cadastrada.')}</td></tr>`;
 };
 document.getElementById('newMatch').onclick=newMatch;
 document.getElementById('matchesTable').onclick=e=>{const b=e.target.closest('[data-finish]');if(b)finishMatch(b.dataset.finish)};
 render();
 function finishMatch(id){
  const m=db.matches.find(x=>x.id===id); if(!m)return;
  modal(`<h2>Resultado da partida</h2><p>${esc(m.teamA)} × ${esc(m.teamB)}</p><form id="resultForm" class="form-grid"><label>Placar ${esc(m.teamA)}<input name="a" type="number" min="0" required></label><label>Placar ${esc(m.teamB)}<input name="b" type="number" min="0" required></label><div class="full modal-actions"><button type="button" class="btn-secondary" data-close>Cancelar</button><button class="btn-primary">Salvar resultado</button></div></form>`);
  document.getElementById('resultForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);m.status='done';m.scoreA=Number(f.get('a'));m.scoreB=Number(f.get('b'));db.results.push({...m});save(db);closeModal();matches()};
  bindClose();
 }
}
function newMatch(){const db=load(),teams=db.teams.filter(t=>t.status==='approved');if(teams.length<2)return alert('Aprove pelo menos duas equipes primeiro.');modal(`<h2>Nova partida</h2><form id="matchForm" class="form-grid"><label>Fase<input name="phase" value="Partida"></label><label>Data e horário<input name="date" type="datetime-local"></label><label>Equipe A<select name="a">${teams.map(t=>`<option>${esc(t.name)}</option>`).join('')}</select></label><label>Equipe B<select name="b">${teams.map(t=>`<option>${esc(t.name)}</option>`).join('')}</select></label><div class="full modal-actions"><button type="button" class="btn-secondary" data-close>Cancelar</button><button class="btn-primary">Salvar partida</button></div></form>`);document.getElementById('matchForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);if(f.get('a')===f.get('b'))return alert('Escolha equipes diferentes.');db.matches.push({id:uid(),phase:f.get('phase'),date:f.get('date'),teamA:f.get('a'),teamB:f.get('b'),status:'scheduled'});save(db);closeModal();matches()};bindClose()}
function results(){const db=load();shell(`<section class="panel"><div class="table-scroll"><table><thead><tr><th>Fase</th><th>Confronto</th><th>Placar</th><th>Status</th><th>Ação</th></tr></thead><tbody>${db.results.map(r=>`<tr><td>${esc(r.phase)}</td><td>${esc(r.teamA)} × ${esc(r.teamB)}</td><td><strong>${r.scoreA} × ${r.scoreB}</strong></td><td><span class="status done">Finalizado</span></td><td>Publicado</td></tr>`).join('')||`<tr><td colspan="5">${empty('Nenhum resultado registrado.')}</td></tr>`}</tbody></table></div></section>`)}
function notices(){const db=load();shell(`<div class="notice-toolbar"><button class="btn-primary" id="newNotice">+ Novo aviso</button></div><div id="noticeList" class="notice-list"></div>`);const render=()=>{document.getElementById('noticeList').innerHTML=db.notices.map(n=>`<article class="notice-item"><div><h3>${esc(n.title)}</h3><p>${esc(n.text)}</p></div><button class="btn-danger" data-remove="${n.id}">Excluir</button></article>`).join('')||empty('Nenhum aviso publicado.')};render();document.getElementById('noticeList').onclick=e=>{const b=e.target.closest('[data-remove]');if(!b)return;db.notices=db.notices.filter(n=>n.id!==b.dataset.remove);save(db);render()};document.getElementById('newNotice').onclick=()=>{modal(`<h2>Novo aviso</h2><form id="noticeForm" class="form-grid"><label>Título<input name="title" required></label><label class="full">Mensagem<textarea name="text" rows="5" required></textarea></label><div class="full modal-actions"><button type="button" class="btn-secondary" data-close>Cancelar</button><button class="btn-primary">Publicar aviso</button></div></form>`);document.getElementById('noticeForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);db.notices.unshift({id:uid(),title:f.get('title'),text:f.get('text'),createdAt:new Date().toISOString()});save(db);closeModal();notices()};bindClose()}}
function settings(){const db=load(),c=db.config;shell(`<section class="panel"><form id="settingsForm" class="form-grid"><label>Nome do campeonato<input id="cfgName" value="${esc(c.name)}" required></label><label>Data<input id="cfgDate" type="date" value="${esc(c.date)}"></label><label>Local<input id="cfgPlace" value="${esc(c.place)}"></label><label>Formato<input id="cfgFormat" value="${esc(c.format)}"></label><label>Quantidade de jogadores<input id="cfgPlayers" type="number" min="1" value="${Number(c.players)||4}"></label><div class="full form-actions"><button class="btn-primary">Salvar configurações</button></div></form></section><section class="panel danger-panel"><h2>Dados do campeonato</h2><p>Use somente se quiser começar a organização do zero.</p><button class="btn-danger" id="clearData">Apagar todos os dados</button></section>`);const cfgName=document.getElementById('cfgName'),cfgDate=document.getElementById('cfgDate'),cfgPlace=document.getElementById('cfgPlace'),cfgFormat=document.getElementById('cfgFormat'),cfgPlayers=document.getElementById('cfgPlayers');document.getElementById('settingsForm').onsubmit=e=>{e.preventDefault();db.config={name:cfgName.value.trim(),date:cfgDate.value,place:cfgPlace.value.trim(),format:cfgFormat.value.trim(),players:Number(cfgPlayers.value)||4};save(db);alert('Configurações salvas.')};document.getElementById('clearData').onclick=()=>{if(confirm('Isso apagará inscrições, equipes, partidas, resultados e avisos. Continuar?')){localStorage.removeItem(DB_KEY);go('dashboard')}}}
function modal(html){const m=document.getElementById('modal');m.innerHTML=`<div class="modal-backdrop" id="backdrop"><div class="modal">${html}</div></div>`;document.getElementById('backdrop').onclick=e=>{if(e.target.id==='backdrop')closeModal()}}
function closeModal(){document.getElementById('modal').innerHTML=''}
function bindClose(){document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModal)}
function bindLinks(){document.querySelectorAll('[data-nav]').forEach(a=>a.onclick=e=>{e.preventDefault();go(a.dataset.nav)})}
function renderPage(p){({dashboard,inscricoes:registrations,equipes:teams,chaveamento:bracket,partidas:matches,resultados,avisos:notices,configuracoes:settings}[p]||dashboard)()}
function loginPage(){const form=document.getElementById('loginForm');if(!form)return;const username=document.getElementById('username'),password=document.getElementById('password'),loginError=document.getElementById('loginError'),togglePassword=document.getElementById('togglePassword');form.onsubmit=e=>{e.preventDefault();const u=username.value.trim(),p=password.value;if(u===CREDENTIALS.user&&p===CREDENTIALS.pass){sessionStorage.setItem(AUTH_KEY,'1');location.href='index.html#dashboard'}else{loginError.textContent='Usuário ou senha inválidos.';password.focus()}};togglePassword.onclick=()=>{password.type=password.type==='password'?'text':'password';togglePassword.textContent=password.type==='password'?'Mostrar':'Ocultar'}}
document.addEventListener('DOMContentLoaded',()=>{if(document.body.classList.contains('login-page')){if(isAuth())location.href='index.html#dashboard';else loginPage();return}guard();nav();window.addEventListener('hashchange',()=>{const page=location.hash.replace('#','');if(pages[page])go(page)});const page=location.hash.replace('#','')||'dashboard';go(page)});
